spring:
  profiles:
    active: test
  application:
    name: fijo-fileservice
mybatis:
  mapper-locations: classpath:mapper/modular/*/*.xml
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000
  management:
    server:
      servlet:
        context-path: /

