spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: fijo123456
    url: jdbc:mysql://172.16.100.190:3306/fijo_base?characterEncoding=utf-8&useSSL=false
  redis:
    host: 172.16.100.190
    password: fijo12345
    port: 6379
    database: 1
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: clientName
    prefer-ip-address: true


